name: ISRAS Validation

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: Iron-Signal-Systems/engineering-standards/.github/workflows/validate-project.yml@29c0839d7a86a66ede9dadd50eebfe3e2ba20c8c
    permissions:
      contents: read
